spring.application.name=AttendMe
server.port=8888

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.peqeqyvchkazlmnoxwob
spring.datasource.password=12345sixTrishaRaye_
spring.datasource.driver-class-name=org.postgresql.Driver

supabase.url=https://peqeqyvchkazlmnoxwob.supabase.co
supabase.service-key=${SUPABASE_KEY}
supabase.storage.bucket=profile-pictures

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation2024AttendanceSystemMustBeLongEnough
jwt.expiration=86400000
jwt.refresh.expiration=604800000

# Google OAuth2
google.client.id=${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID_HERE}
google.client.secret=${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET_HERE}

logging.level.org.springframework.web=INFO
logging.level.edu.cit.cararag.attendme=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE